from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Optional
from datetime import date
from sqlalchemy import create_engine, Column, Integer, String, Date
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import uvicorn
from datetime import date, datetime
from src.paths import *
from src.log import setup_logger

logs=setup_logger(LOG_DIR)
logs.info("FastAPI for incident creation Initiated.....")

# Database setup (SQLite for demo, can swap to Postgres/MySQL easily)
DATABASE_URL = "sqlite:///./sql_db/incidents.db"
engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

# Incident table
class Incident(Base):
    __tablename__ = "incidents"
    id = Column(Integer, primary_key=True, index=True)
    inc_number = Column(String, unique=True, index=True)
    category = Column(String)
    creation_date = Column(String)
    state = Column(String)
    urgency = Column(String)
    assigned_to = Column(String)
    open_by = Column(String)
    short_description = Column(String)
    full_description = Column(String)

     # Agentic system fields
    solution = Column(String)           # Text generated by AI agent
    resolution_time = Column(String)      # When ticket was resolved
    escalated_to = Column(String)       # Team/person if escalated
    resolution_notes = Column(String)   # Extra notes or steps taken
    resolved_by = Column(String)        # "AgenticSystem" or human name

Base.metadata.create_all(bind=engine)



class TicketSchema(BaseModel):
    category: str
    creation_date: date
    state: str
    urgency: str
    assigned_to: str
    open_by: str
    short_description: str
    full_description: str
    solution: Optional[str] = None
    resolution_time: Optional[str] = None
    escalated_to: Optional[str] = None
    resolution_notes: Optional[str] = None
    resolved_by: Optional[str] = None


app = FastAPI(title="ServiceNow Incident Simulator with DB")

# Sequential counter
def generate_inc_number(db):
    last = db.query(Incident).order_by(Incident.id.desc()).first()
    next_id = 1 if not last else last.id + 1
    return f"INC{next_id:05d}"

# Create Incident
@app.post("/snow/incident")
async def create_incident(ticket: TicketSchema):
    db = SessionLocal()
    logs.info("Incident creation Initiated.....")
    inc_number = generate_inc_number(db)
    incident = Incident(
        inc_number=inc_number,
        category=ticket.category,
        creation_date=ticket.creation_date,
        state=ticket.state,
        urgency=ticket.urgency,
        assigned_to=ticket.assigned_to,
        open_by=ticket.open_by,
        short_description=ticket.short_description,
        full_description=ticket.full_description,
        solution=ticket.solution,
        resolution_time=ticket.resolution_time,
        escalated_to=ticket.escalated_to,
        resolution_notes=ticket.resolution_notes,
        resolved_by=ticket.resolved_by
        
    )
    db.add(incident)
    db.commit()
    db.refresh(incident)
    logs.info("Incident creation Done successfully.....")
    return {"inc_number": incident.inc_number, "incident": ticket.dict(), "status": "created"}

# Get Incident
@app.get("/snow/incident/{inc_number}")
async def get_incident(inc_number: str):
    db = SessionLocal()
    incident = db.query(Incident).filter(Incident.inc_number == inc_number).first()
    if not incident:
        raise HTTPException(status_code=404, detail="Incident not found")
    return {"inc_number": incident.inc_number, "incident": incident.__dict__}

# Update Incident
@app.patch("/snow/incident/{inc_number}")
async def update_incident(inc_number: str, updates: dict):
    db = SessionLocal()
    incident = db.query(Incident).filter(Incident.inc_number == inc_number).first()
    if not incident:
        raise HTTPException(status_code=404, detail="Incident not found")
    for key, value in updates.items():
        if hasattr(incident, key):
            setattr(incident, key, value)
    db.commit()
    db.refresh(incident)
    logs.info("Incident Update done successfully.....")
    return {"inc_number": incident.inc_number, "incident": incident.__dict__, "status": "updated"}

# Delete Incident
@app.delete("/snow/incident/{inc_number}")
async def delete_incident(inc_number: str):
    db = SessionLocal()
    incident = db.query(Incident).filter(Incident.inc_number == inc_number).first()
    if not incident:
        raise HTTPException(status_code=404, detail="Incident not found")
    db.delete(incident)
    db.commit()
    logs.info("Incident deletion done successfully.....")
    return {"inc_number": inc_number, "status": "deleted"}

# List All Incidents
@app.get("/snow/incidents")
async def list_incidents():
    db = SessionLocal()
    incidents = db.query(Incident).all()
    logs.info("Incident query done successfully.....")
    return [{"inc_number": i.inc_number, "category": i.category, "state": i.state, "urgency": i.urgency} for i in incidents]


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8080)

